"""empty message

Revision ID: 288cfa6efa2a
Revises: 
Create Date: 2018-04-07 09:59:21.163442

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '288cfa6efa2a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('configs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plexdir', sa.String(length=64), nullable=True),
    sa.Column('time', sa.Time(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('plexdir')
    )
    op.create_table('listeds',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('directory', sa.String(length=64), nullable=True),
    sa.Column('dirfilename', sa.String(length=64), nullable=True),
    sa.Column('filename', sa.String(length=64), nullable=True),
    sa.Column('filenamenoext', sa.String(length=64), nullable=True),
    sa.Column('epnum', sa.String(length=64), nullable=True),
    sa.Column('epseason', sa.String(length=64), nullable=True),
    sa.Column('epshow', sa.String(length=64), nullable=True),
    sa.Column('epname', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dirfilename')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('listeds')
    op.drop_table('configs')
    # ### end Alembic commands ###
