"""“fadded archive directory

Revision ID: 950b7e4e9c6a
Revises: 288cfa6efa2a
Create Date: 2018-04-17 23:42:15.105050

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '950b7e4e9c6a'
down_revision = '288cfa6efa2a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('configs', sa.Column('archivedir', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('configs', 'archivedir')
    # ### end Alembic commands ###
